# Generated by Django 3.2.8 on 2021-10-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='jmfs',
            field=models.ManyToManyField(blank=True, null=True, to='reports.JMF'),
        ),
    ]
