# Generated by Django 3.2.8 on 2021-10-22 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_project_jmfs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jmf',
            name='pdf',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
