# Generated by Django 3.2.8 on 2021-10-22 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_jmf_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='jmf',
            name='mix_size',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jmf',
            name='mix_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='jmfs',
            field=models.ManyToManyField(to='reports.JMF'),
        ),
    ]
