# Generated by Django 3.2.8 on 2021-10-22 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20211021_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jmf',
            name='mix_size',
        ),
        migrations.RemoveField(
            model_name='jmf',
            name='mix_type',
        ),
    ]
