# Generated by Django 3.2.8 on 2021-10-22 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20211021_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='jmf',
            name='mix_size_choices',
            field=models.CharField(choices=[('3/8', '3/8 inch mixture'), ('1/2', '1/2 inch mixture'), ('3/4', '3/4 inch mixture'), ('1', '1 inch mixture')], default='1/2', max_length=50),
        ),
    ]
