# Generated by Django 3.2.8 on 2021-10-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_jmf_mix_size_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='jmf',
            name='mix_type',
            field=models.CharField(choices=[('L1 WC', 'Level 1 Wearing Course'), ('L1 BC', 'Level 1 Binder Course'), ('L1 Base', 'Level 1 Base Course'), ('L2 WC', 'Level 2 Wearing Course'), ('L2 BC', 'Level 2 Binder Course'), ('L2F WC', 'Level 2F Wearing Course'), ('SMA', 'Stone Matrix Asphalt'), ('Dense', 'Dense Graded Asphalt'), ('OGFC', 'Open-Graded Friction Course')], default='L1 WC', max_length=50),
        ),
    ]
