# Generated by Django 3.2.8 on 2021-10-22 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_jmf_mix_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jmf',
            old_name='mix_size_choices',
            new_name='mix_size',
        ),
    ]
