# Generated by Django 3.2.8 on 2021-10-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20211021_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corereadings',
            name='job_type',
            field=models.CharField(choices=[('DOTD', 'LA DOTD'), ('Barber', 'Barber Brothers - Non DOTD Project')], default='DOTD', max_length=10),
        ),
        migrations.AlterField(
            model_name='corereadings',
            name='lane_direction',
            field=models.CharField(choices=[('N', 'North'), ('S', 'South'), ('E', 'East'), ('W', 'West')], default='N', max_length=30),
        ),
    ]
