# Generated by Django 3.2.8 on 2021-10-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20211021_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corereadings',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
