# Generated by Django 3.2.8 on 2021-10-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_alter_corereadings_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='corereadings',
            name='core_id',
            field=models.CharField(default='A1', max_length=30),
            preserve_default=False,
        ),
    ]
