# Generated by Django 3.2.8 on 2021-10-22 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_corereadings_core_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corereadings',
            old_name='core_id',
            new_name='Core ID',
        ),
        migrations.AddField(
            model_name='corereadings',
            name='core_lot',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
