# Generated by Django 3.2.8 on 2021-10-22 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_auto_20211021_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corereadings',
            old_name='Core ID',
            new_name='core_id',
        ),
    ]
