# Generated by Django 3.2.8 on 2021-10-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_rename_core id_corereadings_core_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='corereadings',
            name='core_type',
            field=models.CharField(choices=[('DOTD', 'LA DOTD'), ('Check', 'Check Core')], default='DOTD', max_length=10),
        ),
    ]
