# Generated by Django 3.2.8 on 2021-10-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_corereadings_core_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corereadings',
            name='date_time',
            field=models.DateField(),
        ),
    ]
