# Generated by Django 3.2.8 on 2021-10-24 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_alter_qcreport_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qcreport',
            old_name='date',
            new_name='report_date',
        ),
    ]
