# Generated by Django 3.2.8 on 2021-10-24 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_rename_date_qcreport_report_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corereadings',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='qcreport',
            name='report_date',
        ),
    ]
