# Generated by Django 3.2.8 on 2021-10-24 03:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_auto_20211023_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcreport',
            name='report_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
