# Generated by Django 3.2.8 on 2021-10-24 03:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_qcreport_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='corereadings',
            name='date_time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
