# Generated by Django 3.2.8 on 2021-10-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_corereadings_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='jmf',
            name='project_name',
            field=models.ManyToManyField(to='reports.Project'),
        ),
    ]
