# Generated by Django 3.2.8 on 2021-11-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_jmf_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jmf',
            name='project_name',
            field=models.ManyToManyField(blank=True, to='reports.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='jmfs',
            field=models.ManyToManyField(blank=True, to='reports.JMF'),
        ),
    ]
