# Generated by Django 3.2.8 on 2021-11-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0024_auto_20211102_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='NightlyReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nightly_readings', models.CharField(blank=True, max_length=20)),
                ('report_date', models.DateField()),
                ('jmf', models.ManyToManyField(to='reports.JMF')),
                ('project', models.ManyToManyField(to='reports.Project')),
            ],
        ),
    ]
