# Generated by Django 3.2.8 on 2021-11-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0025_nightlyreadings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nightlyreadings',
            name='report_date',
            field=models.DateField(null=True),
        ),
    ]
