# Generated by Django 3.2.8 on 2021-11-04 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0026_alter_nightlyreadings_report_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nightlyreadings',
            name='jmf',
        ),
    ]
