# Generated by Django 3.2.8 on 2021-11-04 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0027_remove_nightlyreadings_jmf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nightlyreadings',
            name='project',
        ),
    ]
