# Generated by Django 3.2.8 on 2021-11-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0028_remove_nightlyreadings_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='nightlyreadings',
            name='jmf',
            field=models.ManyToManyField(to='reports.JMF'),
        ),
        migrations.AddField(
            model_name='nightlyreadings',
            name='project',
            field=models.ManyToManyField(to='reports.Project'),
        ),
    ]
