# Generated by Django 3.2.8 on 2021-11-17 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0029_auto_20211103_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nightlyreadings',
            old_name='report_date',
            new_name='date',
        ),
    ]
